version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: taskmanager-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskmanager
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: taskmanager-backend
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/taskmanager
      JWT_SECRET: your_jwt_secret_here
      JWT_EXPIRE: 30d
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://localhost:5000/api
    container_name: taskmanager-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
